-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

local map = vim.keymap.set

map("n", "<leader>d", "<Nop>", { desc = "Debug" })

-- DAP core & control flow
map("n", "<leader>db", function()
  require("dap").toggle_breakpoint()
end, { desc = "Toggle Breakpoint" })
map("n", "<leader>dB", function()
  require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, { desc = "Conditional Breakpoint" })
map("n", "<leader>du", function()
  require("dapui").toggle()
end, { desc = "Toggle UI" })
map({ "n", "v" }, "<leader>de", function()
  require("dapui").eval()
end, { desc = "Eval under cursor" })

-- Control flow
map("n", "<leader>dc", function()
  require("dap").continue()
end, { desc = "Continue / Start" })
map("n", "<leader>dC", function()
  require("dap").run_to_cursor()
end, { desc = "Run to Cursor" })
map("n", "<leader>di", function()
  require("dap").step_into()
end, { desc = "Step Into" })
map("n", "<leader>do", function()
  require("dap").step_over()
end, { desc = "Step Over" })
map("n", "<leader>dO", function()
  require("dap").step_out()
end, { desc = "Step Out" })
map("n", "<leader>dp", function()
  require("dap").pause()
end, { desc = "Pause" })
map("n", "<leader>dt", function()
  require("dap").terminate()
end, { desc = "Terminate" })
map("n", "<leader>dr", function()
  require("dap").repl.toggle()
end, { desc = "Toggle REPL" })
map("n", "<leader>dl", function()
  require("dap").run_last()
end, { desc = "Run Last" })

-- Optional classic F-keys (global, always work)
map("n", "<F5>", function()
  require("dap").continue()
end, { desc = "Continue" })
map("n", "<F10>", function()
  require("dap").step_over()
end, { desc = "Step Over" })
map("n", "<F11>", function()
  require("dap").step_into()
end, { desc = "Step Into" })
map("n", "<F12>", function()
  require("dap").step_out()
end, { desc = "Step Out" })
